[environments.env1]
theme = "181583970605"
store = "wemustus.myshopify.com"
password  = "shptka_e2cf0bd8d40676dda15fa730fb7b4692"
ignore = [
    # Ignore ALL JSON templates (client content)
    "templates/*.json",
    "templates/**/*.json",

    # Ignore ALL JSON
    "locales/*.json",
    "locales/*/.json",

    # Ignore ALL JSON sections
    "sections/*.json",
    "sections/**/*.json",

    # Ignore config JSON (dynamic customizer data)
    "config/*.json",
    "config/**/*.json",

    # Ignore Shopify CLI local theme settings
    "shopify.theme.toml"
]

[environments.env2]
theme = "181194129709"
store = "wemustus.myshopify.com"
password  = "shptka_e2cf0bd8d40676dda15fa730fb7b4692"
ignore = [
    # Ignore ALL JSON templates (client content)
    "templates/*.json",
    "templates/**/*.json",
      # Ignore ALL JSON
    "locales/*.json",
    "locales/*/.json",

    # Ignore ALL JSON sections
    "sections/*.json",
    "sections/**/*.json",

    # Ignore config JSON (dynamic customizer data)
    "config/*.json",
    "config/**/*.json",

    # Ignore Shopify CLI local theme settings
    "shopify.theme.toml"
]


[environments.env3]
theme = "170197582125"
store = "wemustus.myshopify.com"
password  = "shptka_e2cf0bd8d40676dda15fa730fb7b4692"
ignore = [
    # Ignore ALL JSON templates (client content)
    "templates/*.json",
    "templates/**/*.json",
      # Ignore ALL JSON
    "locales/*.json",
    "locales/*/.json",

    # Ignore ALL JSON sections
    "sections/*.json",
    "sections/**/*.json",

    # Ignore config JSON (dynamic customizer data)
    "config/*.json",
    "config/**/*.json",

    # Ignore Shopify CLI local theme settings
    "shopify.theme.toml"
]